class_name GlobalEnums
extends Node

enum GameStates { LEVEL_LOAD_STATE, DATA_LOAD_STATE, ACTIVE_GAME_STATE, PAUSED_STATE, QUITTING_GAME_STATE }
enum ScreenModes { FULLSCREEN, FULLSCREEN_WINDOW, WINDOWED }
